In [1]:
import numpy as np
import pandas as pd
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

### 1. Import the Loan data

In [2]:
data = np.genfromtxt('loan-data.csv', delimiter = ';')
loan_raw = data.copy()

In [3]:
loan_raw

array([[        nan,         nan,         nan, ...,         nan,         nan,         nan],
       [48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [4]:
loan_raw.shape

(10001, 14)

In [5]:
# Split loan_raw into header and data

In [6]:
## Header is the first row of loan_raw:
header = np.genfromtxt('loan-data.csv', delimiter = ';', skip_footer= 10000, dtype = 'str')

In [7]:
header

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [8]:
## Data includes the remaining rows of loan_raw:
data = np.genfromtxt('loan-data.csv', delimiter = ';', skip_header= 1)

In [9]:
data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

### 2. Create number-type data and string-type data

In [10]:
data.shape

(10000, 14)

In [11]:
mean = np.nanmean(data, axis = 0)
mean

<ipython-input-11-18b161957216>:1: RuntimeWarning: Mean of empty slice
  mean = np.nanmean(data, axis = 0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [12]:
str_index = np.argwhere(np.isnan(mean) == True).squeeze()
str_index

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [13]:
num_index = np.argwhere(np.isnan(mean) == False).squeeze()
num_index

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [14]:
header_str = header[str_index]
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [15]:
header_num = header[num_index]
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [16]:
# Create temporary fill value to replace the NaN value in number data:
temporary_fill = np.nanmax(data).round(2) + 1
temporary_fill

68616520.0

In [17]:
data_num = np.genfromtxt('loan-data.csv', delimiter = ';',
                                          skip_header= 1,
                                          usecols= num_index,
                                          filling_values= temporary_fill)

In [18]:
data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [19]:
np.isnan(data_num).sum()
# There is no Nan value left in number data.

0

In [20]:
data_str = np.genfromtxt('loan-data.csv', delimiter = ';',
                                          skip_header= 1,
                                          usecols= str_index,
                                          dtype = 'str')

In [21]:
data_str

array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### 3. Clean the String Data

####    3.1 Issue Date

In [22]:
header_str[0]

'issue_d'

In [23]:
data_str[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [24]:
header_str[0] = 'Issue Date'

In [25]:
np.unique(data_str[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [26]:
# Keep only months of the date and change them into the number

In [27]:
data_str[:,0] = np.chararray.strip(data_str[:,0], '-15')

In [28]:
motnh = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

In [29]:
for i in range(12):
    data_str[:,0] = np.where(data_str[:,0] == motnh[i], i+1, data_str[:,0])

In [30]:
data_str[:,0]

array(['5', '', '9', ..., '6', '4', '12'], dtype='<U69')

In [31]:
data_str[:,0] = np.where(data_str[:,0] == '', 0, data_str[:,0])

In [32]:
np.sort(np.unique(data_str[:,0]).astype('int'))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### 3.2 Loan status

In [33]:
header_str[1]

'loan_status'

In [34]:
data_str[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [35]:
header_str[1] = 'Loan status'

In [36]:
np.unique(data_str[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [37]:
status_bad = np.array(['','Charged Off','Default','Late (31-120 days)'])

In [38]:
data_str[:,1] = np.where(np.isin(data_str[:,1], status_bad), 0,1)

In [39]:
np.unique(data_str[:,1])

array(['0', '1'], dtype='<U69')

#### 3.3 Term

In [40]:
header_str[2]

'term'

In [41]:
data_str[:,2]

array([' 36 months', ' 36 months', ' 36 months', ..., ' 36 months', ' 36 months', ' 36 months'],
      dtype='<U69')

In [42]:
header_str[2] = 'Term'

In [43]:
np.unique(data_str[:,2])

array(['', ' 36 months', ' 60 months'], dtype='<U69')

In [44]:
data_str[:,2] = np.chararray.strip(data_str[:,2], ' months')

In [45]:
data_str[:,2] = np.where(data_str[:,2] == '', 60, data_str[:,2])

In [46]:
np.unique(data_str[:,2])

array(['36', '60'], dtype='<U69')

#### 3.4 Grade and Sub Grade

In [47]:
header_str[3]

'grade'

In [48]:
header_str[4]

'sub_grade'

In [49]:
header_str[3], header_str[4] = 'Grade', 'Sub Grade'

In [50]:
data_str[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

In [51]:
data_str[:,4]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [52]:
data_str[:, 3:5]

array([['C', 'C3'],
       ['A', 'A5'],
       ['B', 'B5'],
       ...,
       ['A', 'A5'],
       ['D', 'D2'],
       ['A', 'A4']], dtype='<U69')

In [53]:
np.unique(data_str[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [54]:
np.unique(data_str[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [55]:
# Clean the '' value in Sub grade column:
for i in np.unique(data_str[:,3]):
    data_str[:,4] = np.where((data_str[:,3] == i) & (data_str[:,4] == ''),
                              i + '5',
                              data_str[:,4] )

In [56]:
np.unique(data_str[:,4])

array(['5', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [57]:
data_str[:,4] = np.where(data_str[:,4] == '5', 'H1', data_str[:,4])

In [58]:
np.unique(data_str[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [59]:
# Delete the Grade column:
data_str = np.delete(data_str, 3, axis = 1)

In [60]:
data_str[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [61]:
header_str = np.delete(header_str, 3)

In [62]:
header_str

array(['Issue Date', 'Loan status', 'Term', 'Sub Grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [63]:
# Converting sub grade to number:
np.unique(data_str[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [64]:
np.unique(data_str[:,3]).shape

(36,)

In [65]:
value = list(range(1,37))
key = np.unique(data_str[:,3])
dic = dict(zip(key, value))

In [66]:
dic

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [67]:
data_str[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [68]:
for i in key:
    data_str[:,3] = np.where(data_str[:,3] == i, dic[i], data_str[:,3] )

In [69]:
data_str[:,3]

array(['13', '5', '10', ..., '5', '17', '4'], dtype='<U69')

#### 3.5 Verification Status

In [70]:
header_str[4]

'verification_status'

In [71]:
data_str[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [72]:
header_str[4] = 'Verification Status'

In [73]:
np.unique(data_str[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [74]:
bad_status = ['', 'Not Verified']

In [75]:
data_str[:,4] = np.where(np.isin(data_str[:,4], bad_status), 0,1)

In [76]:
data_str[:,4]

array(['1', '1', '1', ..., '1', '1', '0'], dtype='<U69')

In [77]:
np.unique(data_str[:,4])

array(['0', '1'], dtype='<U69')

#### 3.6 URL

In [78]:
header_str[5]

'url'

In [79]:
data_str[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [80]:
header_str[5] = 'URL'

In [81]:
data_str[:,5] = np.chararray.strip(data_str[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [82]:
a = data_str[:,5].astype(int)
a

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [83]:
b = data_num[:,0].astype(int)
b

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [84]:
np.unique(np.equal(a,b))
# URL column is as same as ID column so we don't need URL column in the data.

array([ True])

In [85]:
data_str = np.delete(data_str,5, axis = 1)
header_str = np.delete(header_str, 5)

In [86]:
data_str

array([['5', '1', '36', '13', '1', 'CA'],
       ['0', '1', '36', '5', '1', 'NY'],
       ['9', '1', '36', '10', '1', 'PA'],
       ...,
       ['6', '1', '36', '5', '1', 'CA'],
       ['4', '1', '36', '17', '1', 'OH'],
       ['12', '1', '36', '4', '0', 'IL']], dtype='<U69')

In [87]:
header_str

array(['Issue Date', 'Loan status', 'Term', 'Sub Grade', 'Verification Status', 'addr_state'],
      dtype='<U19')

#### 3.7 Address State

In [88]:
header_str[5]

'addr_state'

In [89]:
data_str[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [90]:
header_str[5] = 'Address State'

In [91]:
np.unique(data_str[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [92]:
# According to request of the manager, we put these states into 4 regions: West(1), South(2), Mid-West(3), East(4).
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [93]:
data_str[:,5] = np.where(np.isin(data_str[:,5], states_west),1, data_str[:,5])
data_str[:,5] = np.where(np.isin(data_str[:,5], states_south),2, data_str[:,5])
data_str[:,5] = np.where(np.isin(data_str[:,5], states_midwest),3, data_str[:,5])
data_str[:,5] = np.where(np.isin(data_str[:,5], states_east),4, data_str[:,5])

In [94]:
data_str[:,5] = np.where(data_str[:,5] == '',0, data_str[:,5])

In [95]:
np.unique(data_str[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

### 4. Clean the Number Data

In [96]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [97]:
data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

#### 4.1 ID

In [98]:
header_num[0] = 'ID'

In [99]:
np.isin(data_num[:,0], temporary_fill).sum()
# There is no temporary fill value in ID column -> This column is clean already.

0

#### 4.2 Temporary stats

In [100]:
data_num_raw = data[:,num_index]

In [101]:
temporary_stats = np.array([np.nanmin(data_num_raw, axis = 0),
                           np.nanmax(data_num_raw, axis = 0)])

In [102]:
temporary_stats
# This is the min and max value of each number-type column.

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### 4.3 Loaned Amount, Interest Rate, Total Payment, Installment

In [103]:
header_num

array(['ID', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [104]:
header_num = np.array(['ID', 'Loaned Amount', 'Funded Amount', 'Interest Rate', 'Installment', 'Total Payment'])

In [105]:
# Loaned amount
np.isin(data_num[:,1], temporary_fill).sum() 

500

In [106]:
# Interest rate
np.isin(data_num[:,3], temporary_fill).sum() 

6004

In [107]:
# Installment
np.isin(data_num[:,4], temporary_fill).sum() 

501

In [108]:
# Total payment
np.isin(data_num[:,5], temporary_fill).sum() 

500

In [109]:
# We repalce the temporary fill values (NaN) of these columns with max values of each columns correspondingly.
#(According to credit risk regulations of the bank)

In [110]:
for i in [1,3,4,5]:
    data_num[:,i] = np.where(data_num[:,i] == temporary_fill, 
                             temporary_stats[1, i],
                             data_num[:,i])

#### 4.4 Funded amount

In [111]:
np.isin(data_num[:,2], temporary_fill).sum() 

500

In [112]:
# We repalce the temporary fill value (NaN) of Funded amount column with min value.
#(According to credit risk regulations of the bank):
data_num[:,2] = np.where(data_num[:,2] == temporary_fill,
                         temporary_stats[0,2],
                        data_num[:,2])

#### 4.5 Change the currency from EUR to USD

In [113]:
# The currency used in this data is EUR so we need to change it to USD

In [114]:
# Import currency exchange rate:
rate = np.genfromtxt('EUR-USD.csv', delimiter = ',', skip_header= 1, usecols = 3)

In [115]:
rate
# These are EUR/USD exchange rates for each month from January to December

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [116]:
# Creat a exchange rate column base on Date column:

In [117]:
data_str[:,0]

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

In [118]:
exchange_rate = data_str[:,0].astype(int)

In [119]:
for i in range(13):
    exchange_rate = np.where(exchange_rate == i, rate[i-1], exchange_rate)
    

In [120]:
exchange_rate

array([1.1 , 1.09, 1.13, ..., 1.12, 1.11, 1.09])

In [121]:
exchange_rate = exchange_rate.reshape(10000,1)

In [122]:
data_num = np.hstack([data_num, exchange_rate])

In [123]:
data_num

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.09],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [124]:
header_num = np.append(header_num, 'Exchange Rate')

In [125]:
# Change 'Loaned Amount', 'Funded Amount', 'Interest Rate', 'Installment', 'Total Payment' columns to USD

In [126]:
eur_col = [1,2,4,5]

In [127]:
for i in eur_col:
    data_num = np.hstack([data_num, (data_num[:,i]/data_num[:,6]).reshape(10000,1)])

In [128]:
data_num.shape

(10000, 11)

In [129]:
for i in eur_col:
  header_num = np.append(header_num, header_num[i] + ' USD')

In [130]:
header_num

array(['ID', 'Loaned Amount', 'Funded Amount', 'Interest Rate', 'Installment', 'Total Payment',
       'Exchange Rate', 'Loaned Amount USD', 'Funded Amount USD', 'Installment USD',
       'Total Payment USD'], dtype='<U17')

In [131]:
col_reorder = [0,1,7,2,8,3,4,9,5,10,6]

In [132]:
header_num = header_num[col_reorder]

In [133]:
data_num = data_num[:, col_reorder]

In [134]:
data_num

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27437.4 , ...,     4679.7 ,     4279.96,        1.09],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

### 5. Complete the data for analysing

#### 5.1 Stack number and string data

In [135]:
header_num

array(['ID', 'Loaned Amount', 'Loaned Amount USD', 'Funded Amount', 'Funded Amount USD',
       'Interest Rate', 'Installment', 'Installment USD', 'Total Payment', 'Total Payment USD',
       'Exchange Rate'], dtype='<U17')

In [136]:
header_str

array(['Issue Date', 'Loan status', 'Term', 'Sub Grade', 'Verification Status', 'Address State'],
      dtype='<U19')

In [137]:
header_full = np.append(header_num, header_str)
header_full

array(['ID', 'Loaned Amount', 'Loaned Amount USD', 'Funded Amount', 'Funded Amount USD',
       'Interest Rate', 'Installment', 'Installment USD', 'Total Payment', 'Total Payment USD',
       'Exchange Rate', 'Issue Date', 'Loan status', 'Term', 'Sub Grade', 'Verification Status',
       'Address State'], dtype='<U19')

In [138]:
header_full.shape

(17,)

In [139]:
data_full = np.hstack([data_num, data_str.astype(int)])
data_full

array([[48010226. ,    35000. ,    31933.3, ...,       13. ,        1. ,        1. ],
       [57693261. ,    30000. ,    27437.4, ...,        5. ,        1. ,        4. ],
       [59432726. ,    15000. ,    13326.3, ...,       10. ,        1. ,        4. ],
       ...,
       [50415990. ,    10000. ,     8910.3, ...,        5. ,        1. ,        1. ],
       [46154151. ,    35000. ,    31490.9, ...,       17. ,        1. ,        3. ],
       [66055249. ,    10000. ,     9145.8, ...,        4. ,        0. ,        3. ]])

In [140]:
# Short the data by ID:
id_order = np.argsort(data_full[:,0])
id_order

array([2086, 4812, 2353, ..., 4935, 9388, 8415], dtype=int64)

In [141]:
data_full[:,0][id_order]

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [142]:
data_full = data_full[id_order,:]

In [143]:
data_full

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [144]:
data_complete = np.vstack([header_full, data_full])
data_complete

array([['ID', 'Loaned Amount', 'Loaned Amount USD', ..., 'Sub Grade', 'Verification Status',
        'Address State'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [145]:
data_complete.shape

(10001, 17)

#### 5.2 Save the data

In [146]:
np.savetxt('Loan Data Preprocessed.csv', 
           data_complete, 
           delimiter = ',',
           fmt = '%s' )